version: "3.4"

networks:
    internal:
        driver: bridge

services:
    astroid_web:
        image: ahmetkoprulu/astroid:latest
        depends_on:
            - "astroid_db"
            - "astroid_cache"
        container_name: astroid_web
        ports:
            - "80:80"
            - "443:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASTROID_DB_CONNECTION_STRING=Server=astroid_db;Port=5432;Database=astroid;User Id=postgres;Password=1234567890;
            - ASTROID_DB_PROVIDER=2
            - ASTROID_CACHE_CONNECTION_STRING=astroid_cache:6379,password=1234567890,allowAdmin=true
            - ASTROID_BINANCE_TEST_KEY==********
            - ASTROID_BINANCE_TEST_SECRET==********
            - ASTROID_BINANCE_KEY=********
            - ASTROID_BINANCE_SECRET=********
        networks:
            - internal

    astroid_db:
        image: postgres:latest
        container_name: astroid_db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234567890
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - astroid_data:/var/lib/postgresql/data/
        networks:
            - internal

    astroid_cache:
        image: redis:latest
        container_name: astroid_cache
        ports:
            - "6379:6379"
        command: redis-server --requirepass 1234567890
        restart: always
        volumes:
            - astroid_data:/data
        networks:
            - internal

volumes:
    astroid_data:
