FROM node:16-alpine AS node
FROM jenkins/jenkins:alpine

USER root

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN apk add dotnet7-sdk dotnet7-runtime

RUN apk add --update docker openrc
RUN rc-update add docker boot

# Instructions for running the container

#docker run --name jenkins -v "/var/run/docker.sock:/var/run/docker.sock:rw" astroid-jenkins:latest 

